#include <iostream>
#include "version.h"                 //will be generated by CMake
#include "path.h"                    //will be generated by CMake
#include <boost/program_options.hpp> //boost library component for working with cmd
#include <boost/asio.hpp>
#include <boost/asio/ssl.hpp>
#include <openssl/ssl.h>
#include "../ServerLib/include/utilits.hpp"

namespace po = boost::program_options; // namespace for interacting with the console
namespace io = boost::asio;
using namespace std::placeholders;

// a function that describes the commands for cmd and their implementation
static void cmd_parse(const int ac, char **av)
{
    po::options_description desc("Allowed options");

    desc.add_options()("help,h", "produce help message")("version,v", "Show version of program")("path,p", "Show path");

    po::variables_map vm;
    po::store(po::parse_command_line(ac, av, desc), vm);
    po::notify(vm);

    if (vm.count("help"))
    {
        std::cout << desc << "\n";
        exit(0);
    }

    else if (vm.count("version"))
    {
        std::cout << "Version: " << g_version << std::endl;
        exit(0);
    }

    else if (vm.count("path"))
    {
        std::cout << "Path to source of the program: " << g_sourse_path << std::endl;
        std::cout << "Path to binary of the program: " << g_binary_path << std::endl;
        exit(0);
    }
}